### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by kevklam** [Willy-Kimura/SharpClipboard#11]
A couple suggestions I came across when experimenting with clipboard apis:
 - Consider moving to AddClipboardFormatListener instead of SetClipboardViewer, as MSDN suggests the latter is legacy and more likely to break things badly if there is a bug. It's simpler to manage, as well. 

- I've had some luck using WPF "new HwndSource()" to immediately create a message-only window (I.e. By specifying parent window=HWND_MESSAGE_ONLY), which is very lightweight and immediately gives you a handle instead of waiting for windows forms to initialize and call back with OnLoad. I noticed also that you have a 1 second delay before enabling monitoring - I wasn't sure if this was to resolve a race condition regarding window initialization, but it seems unnecessary when using new HwndSource.

**Comment by Willy-Kimura** [comment]
Very valuable suggestions indeed. Thank you.

Upon investigation, something I definitely considered taking a further look at and probably introduce in a near release is on implementing a *message-only* window. It is simpler compared to the library's current working model and might prove very beneficial internally.

As for the 1-second delay and likewise the Timer, since Windows components do not have an actual loading mechanism, this was a necessary measure and a much simplified way of invoking the library once an application starts; after that the Timer shuts down. Probably in future the Timer implementation can be explored to fit some unique scenarios.
